# -*- coding: utf-8 -*-
"""
autostart.py — 开机自启安装/卸载（无窗口后台运行）

用途: 让 XinHaoTa 登录 Windows 后自动在后台运行（pythonw 无窗口），
      之后随时打开 http://127.0.0.1:8090 即可使用，无需手动启动。

用法:
  python scripts/autostart.py install    安装（登录自启 + 立即后台启动）
  python scripts/autostart.py uninstall  卸载（取消自启 + 停止后台服务）

原理: 在用户 Startup 文件夹放一个 .vbs（内容指向本仓库 pythonw web_server.py 8090，
      ws.Run ...,0,False 无窗口静默）。卸载时删除该 vbs 并结束对应进程。
"""
from __future__ import annotations
import os, sys, subprocess

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # 仓库根
VBS_NAME = "XinHaoTa-autostart.vbs"
PORT = 8090


def _startup_dir():
    """用户 Startup 文件夹（登录时自动执行其中的文件）。"""
    return os.path.join(os.environ.get("APPDATA", ""),
                        "Microsoft", "Windows", "Start Menu",
                        "Programs", "Startup")


def _vbs_path():
    return os.path.join(_startup_dir(), VBS_NAME)


def _running_pids():
    """找到正在跑的 XinHaoTa web_server 进程 PID（pythonw/python）。"""
    pids = []
    for name in ("pythonw.exe", "python.exe"):
        try:
            out = subprocess.check_output(
                ["powershell", "-NoProfile", "-Command",
                 f"Get-CimInstance Win32_Process -Filter \"Name='{name}'\" | "
                 f"Where-Object {{ $_.CommandLine -match 'web_server\\.py {PORT}' }} | "
                 f"Select-Object -ExpandProperty ProcessId"],
                text=True, timeout=10, errors="replace")
        except Exception:
            continue
        for ln in out.splitlines():
            ln = ln.strip()
            if ln.isdigit():
                pids.append(ln)
    return pids


def _vbs_str(s: str) -> str:
    """VBS 字符串字面量安全转义：内部双引号写作 ""（VB/VBS 约定）。"""
    return s.replace('"', '""')


def install():
    startup = _startup_dir()
    os.makedirs(startup, exist_ok=True)
    # vbs 内容: 切到仓库根, 无窗口启动 pythonw web_server.py 8090
    # 路径经 _vbs_str 转义——仓库路径即使含双引号也不会破坏 VBS 语法
    vbs = (
        "' XinHaoTa signal tower - autostart (generated by scripts/autostart.py)\n"
        "Set ws = CreateObject(\"Wscript.Shell\")\n"
        f"ws.CurrentDirectory = \"{_vbs_str(BASE)}\"\n"
        f"ws.Run \"pythonw.exe web_server.py {PORT}\", 0, False\n"
    )
    vbs_path = _vbs_path()
    with open(vbs_path, "w", encoding="ascii") as f:
        f.write(vbs)
    # 立即后台启动一次（若尚未运行）
    if not _running_pids():
        subprocess.Popen(["pythonw.exe", os.path.join(BASE, "web_server.py"), str(PORT)],
                         cwd=BASE)
    print(f"[OK] 开机自启已安装: {vbs_path}")
    print(f"[OK] 平台后台运行中 -> http://127.0.0.1:{PORT}/  (登录 Windows 后也会自动启动)")


def uninstall():
    vbs_path = _vbs_path()
    if os.path.exists(vbs_path):
        os.remove(vbs_path)
        print(f"[OK] 已取消开机自启: {vbs_path}")
    else:
        print("[i] 未找到自启项（可能未安装过）")
    for pid in _running_pids():
        try:
            subprocess.run(["taskkill", "/PID", pid, "/F"],
                           capture_output=True, timeout=8)
            print(f"[OK] 已停止后台服务 PID {pid}")
        except Exception:
            pass
    if not _running_pids():
        print("[OK] 后台服务已停止")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "install"
    if cmd == "install":
        install()
    elif cmd == "uninstall":
        uninstall()
    else:
        print("用法: python scripts/autostart.py install|uninstall")
        sys.exit(1)
